### PR TITLE
Make java_proto_library work

### PR DESCRIPTION
**Pull request by Jonpez2**
Remap the outer classname so that an invocation of java_proto_library doesn't get a classname collision

### CODE REVIEW

**Comment by EdSchouten** [comment]
Looks good! Could you address the CI failure? Will merge upon success.

**Comment by Jonpez2** [comment]
I think I did it

**Comment by Jonpez2** [comment]
Apparently not. What is that test complaining about? I haven’t touched any byte arrays…

**Comment by EdSchouten** [comment]
We check in the resulting .pb.yo files, to make 'go get' work. Take a look at the .github/workflows files to see what command you need to run to regenerate them.

**Comment by Jonpez2** [comment]
OK, sorry, I'm not seeing any commands in the workflows that do anything but clang-format on the protos?  I'm sorry I'm being dumb!

**Comment by EdSchouten** [comment]
```
            find . bazel-bin/pkg/proto -name '*.pb.go' -delete || true
            bazel build $(bazel query 'kind("go_proto_library", //...)')
            find bazel-bin/pkg/proto -name '*.pb.go' | while read f; do
              cat $f > $(echo $f | sed -e 's|.*/pkg/proto/|pkg/proto/|')
            done
```

**Comment by Jonpez2** [comment]
Oh duh my fork is out of date, I'm sorry

**Comment by Jonpez2** [comment]
shall we try this one?  Maybe I got it right...

**Pull request merged**
